"""Initial migration.

Revision ID: 15755e5084f4
Revises: 
Create Date: 2024-08-25 14:06:39.893157

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '15755e5084f4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cliente')
    op.drop_table('medidor')
    op.drop_table('empresa')
    op.drop_table('endereco_entrega')
    op.drop_table('projetos')
    op.drop_table('especificador')
    op.drop_table('endereco_comercial')
    op.drop_table('liberador')
    op.drop_table('contrato')
    op.drop_table('usuario')
    op.drop_table('projetista')
    op.drop_table('loja')
    op.drop_table('montador')
    op.drop_table('conjuge')
    op.drop_table('endereco_residencial')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('endereco_residencial',
    sa.Column('id_endereco_residencial', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('rua', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('numero', mysql.VARCHAR(length=10), nullable=True),
    sa.Column('complemento', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('bairro', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('cidade', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('estado', mysql.VARCHAR(length=2), nullable=True),
    sa.Column('cep', mysql.VARCHAR(length=8), nullable=True),
    sa.PrimaryKeyConstraint('id_endereco_residencial'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('conjuge',
    sa.Column('id_conjuge', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nome', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('cpf', mysql.VARCHAR(length=11), nullable=True),
    sa.Column('cnpj', mysql.VARCHAR(length=14), nullable=True),
    sa.Column('telefone', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('email', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('fk_cliente', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('fk_empresa', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('fk_endereco_residencial', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('fk_endereco_entrega', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['fk_cliente'], ['cliente.id_cliente'], name='conjuge_ibfk_1'),
    sa.ForeignKeyConstraint(['fk_empresa'], ['empresa.id_empresa'], name='conjuge_ibfk_2'),
    sa.ForeignKeyConstraint(['fk_endereco_entrega'], ['endereco_entrega.id_endereco_entrega'], name='conjuge_ibfk_4'),
    sa.ForeignKeyConstraint(['fk_endereco_residencial'], ['endereco_residencial.id_endereco_residencial'], name='conjuge_ibfk_3'),
    sa.PrimaryKeyConstraint('id_conjuge'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('montador',
    sa.Column('id_montador', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nome', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('cpf', mysql.VARCHAR(length=11), nullable=True),
    sa.Column('telefone', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('email', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('fk_endereco_residencial', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('fk_endereco_entrega', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('fk_empresa', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('fk_loja', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('fk_cliente', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('fk_conjuge', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['fk_cliente'], ['cliente.id_cliente'], name='montador_ibfk_5'),
    sa.ForeignKeyConstraint(['fk_conjuge'], ['conjuge.id_conjuge'], name='montador_ibfk_6'),
    sa.ForeignKeyConstraint(['fk_empresa'], ['empresa.id_empresa'], name='montador_ibfk_3'),
    sa.ForeignKeyConstraint(['fk_endereco_entrega'], ['endereco_entrega.id_endereco_entrega'], name='montador_ibfk_2'),
    sa.ForeignKeyConstraint(['fk_endereco_residencial'], ['endereco_residencial.id_endereco_residencial'], name='montador_ibfk_1'),
    sa.ForeignKeyConstraint(['fk_loja'], ['loja.id_loja'], name='montador_ibfk_4'),
    sa.PrimaryKeyConstraint('id_montador'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('loja',
    sa.Column('id_loja', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nome', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('gerente', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('fk_empresa', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['fk_empresa'], ['empresa.id_empresa'], name='loja_ibfk_1'),
    sa.PrimaryKeyConstraint('id_loja'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('projetista',
    sa.Column('id_projetista', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nome', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('cpf', mysql.VARCHAR(length=11), nullable=True),
    sa.Column('telefone', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('email', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('fk_empresa', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('fk_loja', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('fk_cliente', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('fk_especificador', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('fk_conjuge', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['fk_cliente'], ['cliente.id_cliente'], name='projetista_ibfk_3'),
    sa.ForeignKeyConstraint(['fk_conjuge'], ['conjuge.id_conjuge'], name='projetista_ibfk_5'),
    sa.ForeignKeyConstraint(['fk_empresa'], ['empresa.id_empresa'], name='projetista_ibfk_1'),
    sa.ForeignKeyConstraint(['fk_especificador'], ['especificador.id_especificador'], name='projetista_ibfk_4'),
    sa.ForeignKeyConstraint(['fk_loja'], ['loja.id_loja'], name='projetista_ibfk_2'),
    sa.PrimaryKeyConstraint('id_projetista'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('usuario',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nome', mysql.VARCHAR(length=80), nullable=False),
    sa.Column('email', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('senha', mysql.VARCHAR(length=120), nullable=False),
    sa.Column('data_cadastro', sa.DATE(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('contrato',
    sa.Column('id_contrato', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('numero_contrato', mysql.VARCHAR(length=8), nullable=True),
    sa.Column('data_venda', sa.DATE(), nullable=True),
    sa.Column('data_medicao', sa.DATE(), nullable=True),
    sa.Column('data_revisao', sa.DATE(), nullable=True),
    sa.Column('data_tecnico', sa.DATE(), nullable=True),
    sa.Column('data_compra', sa.DATE(), nullable=True),
    sa.Column('data_entrega', sa.DATE(), nullable=True),
    sa.Column('data_montagem', sa.DATE(), nullable=True),
    sa.Column('data_fim', sa.DATE(), nullable=True),
    sa.Column('valor_venda', mysql.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('valor_revisao', mysql.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('valor_liberado', mysql.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('valor_compra', mysql.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('valor_montagem', mysql.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('fk_cliente', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('fk_projetista', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('fk_medidor', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('fk_liberador', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('fk_montador', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('fk_especificador', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['fk_cliente'], ['cliente.id_cliente'], name='contrato_ibfk_1'),
    sa.ForeignKeyConstraint(['fk_especificador'], ['especificador.id_especificador'], name='contrato_ibfk_6'),
    sa.ForeignKeyConstraint(['fk_liberador'], ['liberador.id_liberador'], name='contrato_ibfk_4'),
    sa.ForeignKeyConstraint(['fk_medidor'], ['medidor.id_medidor'], name='contrato_ibfk_3'),
    sa.ForeignKeyConstraint(['fk_montador'], ['montador.id_montador'], name='contrato_ibfk_5'),
    sa.ForeignKeyConstraint(['fk_projetista'], ['projetista.id_projetista'], name='contrato_ibfk_2'),
    sa.PrimaryKeyConstraint('id_contrato'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('liberador',
    sa.Column('id_liberador', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nome', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('cpf', mysql.VARCHAR(length=11), nullable=True),
    sa.Column('telefone', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('email', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('fk_empresa', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('fk_loja', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('fk_cliente', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('fk_conjuge', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['fk_cliente'], ['cliente.id_cliente'], name='liberador_ibfk_3'),
    sa.ForeignKeyConstraint(['fk_conjuge'], ['conjuge.id_conjuge'], name='liberador_ibfk_4'),
    sa.ForeignKeyConstraint(['fk_empresa'], ['empresa.id_empresa'], name='liberador_ibfk_1'),
    sa.ForeignKeyConstraint(['fk_loja'], ['loja.id_loja'], name='liberador_ibfk_2'),
    sa.PrimaryKeyConstraint('id_liberador'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('endereco_comercial',
    sa.Column('id_endereco_comercial', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('rua', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('numero', mysql.VARCHAR(length=10), nullable=True),
    sa.Column('complemento', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('bairro', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('cidade', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('estado', mysql.VARCHAR(length=2), nullable=True),
    sa.Column('cep', mysql.VARCHAR(length=8), nullable=True),
    sa.PrimaryKeyConstraint('id_endereco_comercial'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('especificador',
    sa.Column('id_especificador', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nome', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('cpf', mysql.VARCHAR(length=11), nullable=True),
    sa.Column('telefone', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('email', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('fk_empresa', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('fk_loja', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('fk_cliente', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('fk_conjuge', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['fk_cliente'], ['cliente.id_cliente'], name='especificador_ibfk_3'),
    sa.ForeignKeyConstraint(['fk_conjuge'], ['conjuge.id_conjuge'], name='especificador_ibfk_4'),
    sa.ForeignKeyConstraint(['fk_empresa'], ['empresa.id_empresa'], name='especificador_ibfk_1'),
    sa.ForeignKeyConstraint(['fk_loja'], ['loja.id_loja'], name='especificador_ibfk_2'),
    sa.PrimaryKeyConstraint('id_especificador'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('projetos',
    sa.Column('id_projeto', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('ambiente', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('promob_venda', sa.BLOB(), nullable=True),
    sa.Column('promob_medidor', sa.BLOB(), nullable=True),
    sa.Column('promob_liberador', sa.BLOB(), nullable=True),
    sa.Column('promob_compra', sa.BLOB(), nullable=True),
    sa.Column('lista_venda', sa.BLOB(), nullable=True),
    sa.Column('lista_liberada', sa.BLOB(), nullable=True),
    sa.Column('lista_compra', sa.BLOB(), nullable=True),
    sa.Column('caminho_venda', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('caminho_medida', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('caminho_liberado', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('caminho_compra', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('valor_venda', mysql.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('valor_revisao', mysql.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('valor_liberado', mysql.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('valor_compra', mysql.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('data_venda', sa.DATE(), nullable=True),
    sa.Column('data_medicao', sa.DATE(), nullable=True),
    sa.Column('data_revisao', sa.DATE(), nullable=True),
    sa.Column('data_tecnico', sa.DATE(), nullable=True),
    sa.Column('data_compra', sa.DATE(), nullable=True),
    sa.Column('fk_contrato', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('fk_cliente', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('fk_especificador', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('fk_projetista', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('fk_medidor', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('fk_liberador', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['fk_cliente'], ['cliente.id_cliente'], name='projetos_ibfk_2'),
    sa.ForeignKeyConstraint(['fk_contrato'], ['contrato.id_contrato'], name='projetos_ibfk_1'),
    sa.ForeignKeyConstraint(['fk_especificador'], ['especificador.id_especificador'], name='projetos_ibfk_3'),
    sa.ForeignKeyConstraint(['fk_liberador'], ['liberador.id_liberador'], name='projetos_ibfk_6'),
    sa.ForeignKeyConstraint(['fk_medidor'], ['medidor.id_medidor'], name='projetos_ibfk_5'),
    sa.ForeignKeyConstraint(['fk_projetista'], ['projetista.id_projetista'], name='projetos_ibfk_4'),
    sa.PrimaryKeyConstraint('id_projeto'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('endereco_entrega',
    sa.Column('id_endereco_entrega', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('rua', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('numero', mysql.VARCHAR(length=10), nullable=True),
    sa.Column('complemento', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('bairro', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('cidade', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('estado', mysql.VARCHAR(length=2), nullable=True),
    sa.Column('cep', mysql.VARCHAR(length=8), nullable=True),
    sa.PrimaryKeyConstraint('id_endereco_entrega'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('empresa',
    sa.Column('id_empresa', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nome_empresa', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('nome_fantasia', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('cnpj', mysql.VARCHAR(length=14), nullable=True),
    sa.Column('razao_social', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('data_fundacao', sa.DATE(), nullable=True),
    sa.Column('telefone', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('email', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('website', mysql.VARCHAR(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id_empresa'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('medidor',
    sa.Column('id_medidor', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nome', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('cpf', mysql.VARCHAR(length=11), nullable=True),
    sa.Column('telefone', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('email', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('fk_empresa', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('fk_loja', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('fk_cliente', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('fk_conjuge', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['fk_cliente'], ['cliente.id_cliente'], name='medidor_ibfk_3'),
    sa.ForeignKeyConstraint(['fk_conjuge'], ['conjuge.id_conjuge'], name='medidor_ibfk_4'),
    sa.ForeignKeyConstraint(['fk_empresa'], ['empresa.id_empresa'], name='medidor_ibfk_1'),
    sa.ForeignKeyConstraint(['fk_loja'], ['loja.id_loja'], name='medidor_ibfk_2'),
    sa.PrimaryKeyConstraint('id_medidor'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('cliente',
    sa.Column('id_cliente', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nome', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('cpf', mysql.VARCHAR(length=11), nullable=True),
    sa.Column('cnpj', mysql.VARCHAR(length=14), nullable=True),
    sa.Column('telefone', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('email', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('fk_empresa', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('fk_endereco_residencial', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('fk_endereco_entrega', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['fk_empresa'], ['empresa.id_empresa'], name='cliente_ibfk_1'),
    sa.ForeignKeyConstraint(['fk_endereco_entrega'], ['endereco_entrega.id_endereco_entrega'], name='cliente_ibfk_3'),
    sa.ForeignKeyConstraint(['fk_endereco_residencial'], ['endereco_residencial.id_endereco_residencial'], name='cliente_ibfk_2'),
    sa.PrimaryKeyConstraint('id_cliente'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
